import { useState } from "react";
import { Anvil, CarFront, Crosshair, Diamond, Heart, Package, Shield, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MATERIALS, gearCost, infuseGear, upgradeGear, type GearItem, type GearSlot } from "@/game/inventory";
import type { PlayerProgression } from "@/game/progression";
import inventoryArt from "@/assets/inventory-reference.jpg.asset.json";
import { CornerBrackets } from "./HudChrome";

const SLOTS: { id: GearSlot; label: string }[] = [
  { id: "primary", label: "Primary" }, { id: "secondary", label: "Secondary" }, { id: "heavy", label: "Heavy" },
  { id: "helmet", label: "Helmet" }, { id: "chest", label: "Chest" }, { id: "gauntlets", label: "Gauntlets" },
  { id: "classItem", label: "Class Item" }, { id: "legs", label: "Legs" }, { id: "vehicle", label: "Vehicle" },
];
const iconFor = (slot: GearSlot) => slot === "vehicle" ? CarFront : ["primary", "secondary", "heavy"].includes(slot) ? Crosshair : Shield;

export function InventoryWindow({ progression, onProgression, onClose }: { progression: PlayerProgression; onProgression: (next: PlayerProgression) => void; onClose: () => void }) {
  const [selectedId, setSelectedId] = useState(progression.inventory[0]?.id ?? "");
  const [tab, setTab] = useState<"ARMORY" | "MATERIALS" | "CRAFTING">("ARMORY");
  const selected = progression.inventory.find((item) => item.id === selectedId);
  const cost = selected ? gearCost(selected) : null;
  const equipped = (item: GearItem) => progression.equippedGear[item.slot] === item.id;
  const toggleFavorite = (item: GearItem) => onProgression({ ...progression, inventory: progression.inventory.map((entry) => entry.id === item.id ? { ...entry, favorite: !entry.favorite } : entry) });
  const dismantle = (item: GearItem) => {
    if (item.favorite || equipped(item) || item.source === "Starting loadout") return;
    onProgression({ ...progression, inventory: progression.inventory.filter((entry) => entry.id !== item.id), materials: { ...progression.materials, scrapMetal: (progression.materials.scrapMetal ?? 0) + 2 } });
    setSelectedId(progression.inventory.find((entry) => entry.id !== item.id)?.id ?? "");
  };
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-background/95 text-foreground backdrop-blur-xl hud-scanline" role="dialog" aria-modal="true" aria-label="Inventory">
    <div className="mx-auto max-w-7xl px-4 py-5 sm:px-7">
      <header className="flex items-start justify-between gap-3 border-b border-primary/30 pb-5"><div><p className="hud-label">WF / Operator systems</p><h2 className="mt-1 font-mono text-3xl font-semibold" style={{ textShadow: "0 0 18px color-mix(in oklch, var(--primary) 30%, transparent)" }}>INVENTORY <span className="text-muted-foreground">// FRACTURE ADEPT IV</span></h2></div><Button size="icon" variant="outline" className="hud-panel border-0" onClick={onClose} aria-label="Close inventory"><X /></Button></header>
      <div className="mt-4 flex gap-2" role="tablist" aria-label="Inventory sections">{(["ARMORY", "MATERIALS", "CRAFTING"] as const).map((name) => <Button key={name} role="tab" aria-selected={tab === name} variant={tab === name ? "default" : "outline"} className={tab === name ? "hud-glow" : "hud-panel border-0"} onClick={() => setTab(name)}>{name}</Button>)}</div>
      <div className="mt-5 grid gap-6 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.4fr)_minmax(16rem,0.75fr)]">
        <section className="min-w-0"><p className="hud-label mb-3">Loadout / {Object.keys(progression.equippedGear).length} equipped</p><div className="grid grid-cols-2 gap-2">{SLOTS.map(({ id, label }) => { const item = progression.inventory.find((entry) => entry.id === progression.equippedGear[id]); const Icon = iconFor(id); return <Button key={id} variant="ghost" onClick={() => item && setSelectedId(item.id)} className={`hud-panel relative h-auto min-h-20 flex-col items-start gap-0 p-2 text-left whitespace-normal ${item && selectedId === item.id ? "hud-glow" : ""}`}><CornerBrackets size={6} /><Icon className="mb-1 size-4 text-primary" style={{ filter: "drop-shadow(0 0 3px var(--primary))" }} /><span className="hud-label !text-[9px]">{label}</span><span className="block text-xs font-semibold">{item?.name ?? "Empty"}</span></Button>; })}</div><div className="mt-5 border-t border-primary/20 pt-4"><p className="hud-label">Field condition</p><div className="mt-2 grid grid-cols-3 gap-2 text-center text-xs">{[["89%", "DURABILITY"], [String(progression.inventory.filter(equipped).reduce((sum, item) => sum + item.power, 0)), "POWER"], ["76%", "STABILITY"]].map(([value, label]) => <span key={label} className="hud-panel relative p-2 text-primary"><CornerBrackets size={5} />{value}<small className="hud-label !mb-0 block">{label}</small></span>)}</div></div></section>
        <section className="min-w-0"><div className="flex justify-between hud-label"><span>Armory</span><span>{progression.inventory.length} / 120 Capacity</span></div>{tab === "ARMORY" ? <div className="mt-3 grid grid-cols-3 gap-2 sm:grid-cols-4 xl:grid-cols-5">{progression.inventory.map((item) => { const Icon = iconFor(item.slot); return <Button key={item.id} variant="ghost" onClick={() => setSelectedId(item.id)} className={`hud-panel relative h-24 flex-col items-start justify-between p-2 text-left whitespace-normal ${selectedId === item.id ? "hud-glow" : ""}`}><CornerBrackets size={5} /><Icon className="size-5 text-primary" style={{ filter: "drop-shadow(0 0 3px var(--primary))" }} /><span className="line-clamp-2 w-full text-[10px] leading-tight">{item.name}</span><span className="text-[9px] text-muted-foreground">{item.element} · {item.power}</span>{item.favorite && <Heart className="absolute right-1 top-1 size-3 fill-current text-destructive" style={{ filter: "drop-shadow(0 0 3px var(--destructive))" }} />}</Button>; })}</div> : tab === "MATERIALS" ? <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{Object.entries(MATERIALS).map(([id, material]) => <div key={id} className="hud-panel relative min-h-24 p-3"><CornerBrackets /><Diamond className="size-4 text-primary" style={{ filter: "drop-shadow(0 0 3px var(--primary))" }} /><p className="mt-2 text-sm font-medium">{material.name} <b className="text-primary">×{progression.materials[id as keyof typeof MATERIALS] ?? 0}</b></p><p className="mt-1 text-[10px] text-muted-foreground">{material.source}</p></div>)}</div> : <div className="hud-panel hud-glow relative mt-3 p-5"><CornerBrackets /><Anvil className="size-6 text-primary" style={{ filter: "drop-shadow(0 0 4px var(--primary))" }} /><h3 className="mt-3 text-lg font-semibold">Field forge</h3><p className="mt-2 text-sm text-muted-foreground">Select gear to upgrade its power or apply an elemental infusion. Materials come from regional troops, bosses, and salvage.</p><img src={inventoryArt.url} alt="Inventory concept showing armor, weapons, materials and loadout" className="mt-5 w-full border border-primary/30" /></div>}</section>
        <aside className="min-w-0 border-t border-primary/20 pt-4 lg:border-l lg:border-t-0 lg:pl-5 lg:pt-0">{selected ? <><p className="hud-label">{selected.slot} / level {selected.level}</p><h3 className="mt-2 text-2xl font-semibold">{selected.name}</h3><div className="hud-panel hud-glow relative my-5 flex aspect-[4/3] items-center justify-center"><CornerBrackets /><Package className="size-20 text-primary/70" strokeWidth={0.7} style={{ filter: "drop-shadow(0 0 8px color-mix(in oklch, var(--primary) 50%, transparent))" }} /></div><dl className="grid grid-cols-2 gap-y-2 border-b border-primary/20 pb-4 text-sm"><dt className="text-muted-foreground">Power</dt><dd>{selected.power}</dd><dt className="text-muted-foreground">Element</dt><dd>{selected.element}</dd><dt className="text-muted-foreground">Source</dt><dd>{selected.source}</dd></dl><div className="mt-4 flex flex-wrap gap-2"><Button size="sm" className="hud-glow" disabled={equipped(selected)} onClick={() => onProgression({ ...progression, equippedGear: { ...progression.equippedGear, [selected.slot]: selected.id } })}><Shield /> {equipped(selected) ? "Equipped" : "Equip"}</Button><Button size="sm" variant="outline" className="hud-panel border-0" onClick={() => toggleFavorite(selected)}><Heart className={selected.favorite ? "fill-current" : ""} /> {selected.favorite ? "Favorited" : "Favorite"}</Button><Button size="sm" variant="outline" className="hud-panel border-0" disabled={selected.favorite || equipped(selected) || selected.source === "Starting loadout"} onClick={() => dismantle(selected)}><Trash2 /> Dismantle</Button></div><div className="mt-6 border-t border-primary/20 pt-4"><p className="hud-label">Upgrade & infusion</p><Button className="hud-panel mt-3 w-full border-0" variant="outline" disabled={!cost || (progression.materials[cost.material] ?? 0) < cost.amount} onClick={() => onProgression(upgradeGear(progression, selected.id))}><Anvil /> Upgrade · {cost ? `${cost.amount} ${MATERIALS[cost.material].name}` : ""}</Button><div className="mt-3 grid grid-cols-3 gap-1">{(["THERMAL", "CRYO", "ARC", "BIO"] as const).map((element) => { const material = element === "THERMAL" ? "thermalShards" : element === "CRYO" ? "cryoCrystal" : element === "BIO" ? "bioCatalyst" : "microCircuits"; return <Button key={element} size="sm" variant="outline" className="hud-panel h-auto min-h-10 whitespace-normal border-0 text-[10px]" disabled={selected.element === element || (progression.materials[material] ?? 0) < 3} onClick={() => onProgression(infuseGear(progression, selected.id, element))}>{element}</Button>; })}</div><p className="mt-2 text-xs text-muted-foreground">Infusion costs 3 matching materials.</p></div></> : <p className="text-sm text-muted-foreground">No item selected.</p>}</aside>
      </div>
    </div>
  </div>;
}