import { ChevronLeft, ChevronRight, Cpu, Settings, Shield } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { APPEARANCES, CLASSES, DEFAULT_SUBCLASS, SUBCLASSES, appearanceById, classById, type AppearanceId, type ClassId, type SubclassId } from "@/game/loadout";
import { OperatorPreview } from "./OperatorPreview";

export type { ClassId } from "@/game/loadout";
type Stage = "CLASS" | "SUBCLASS" | "APPEARANCE";
export type Deployment = { classId: ClassId; subclassId: SubclassId; appearanceId: AppearanceId };
const STAGES: Stage[] = ["CLASS", "SUBCLASS", "APPEARANCE"];

export function StartMenu({ onDeploy, onSettings, best }: { onDeploy: (deployment: Deployment) => void; onSettings: () => void; best: { credits: number; kills: number } | null }) {
  const [classId, setClassId] = useState<ClassId>("TITAN");
  const [subclassId, setSubclassId] = useState<SubclassId>("SHIELD_TITAN");
  const [appearanceId, setAppearanceId] = useState<AppearanceId>("RANGER");
  const [stage, setStage] = useState<Stage>("CLASS");
  const [bodyFrame, setBodyFrame] = useState<"LIGHT" | "BALANCED" | "HEAVY">("BALANCED");
  const [coreType, setCoreType] = useState<"LOGIC" | "COMBAT" | "SYSTEM" | "ADAPTIVE">("ADAPTIVE");
  const stageIndex = STAGES.indexOf(stage);
  const selectedClass = CLASSES.find((item) => item.id === classId) ?? classById(classId);
  const appearance = appearanceById(appearanceId);
  const subclasses = SUBCLASSES.filter((item) => item.classId === classId);
  const selectClass = (id: ClassId) => { setClassId(id); setSubclassId(DEFAULT_SUBCLASS[id]); };
  const next = () => { const nextStage = STAGES[stageIndex + 1]; if (nextStage) setStage(nextStage); else onDeploy({ classId, subclassId, appearanceId }); };
  const back = () => { const previous = STAGES[stageIndex - 1]; if (previous) setStage(previous); };

  return <div className="fixed inset-0 z-50 overflow-y-auto bg-background">
    <div className="pointer-events-none absolute inset-0 fracture-grid opacity-50" />
    <div className="relative mx-auto flex min-h-full max-w-6xl flex-col px-4 py-5 sm:px-8">
      <header className="flex items-start justify-between border-b border-border/70 pb-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.45em] text-primary">Season 01 · The First Collapse</p><h1 className="mt-2 font-mono text-3xl font-bold tracking-[0.16em] sm:text-5xl">WORLD FRACTURE</h1></div><Button variant="ghost" size="icon" onClick={onSettings} aria-label="Open settings"><Settings /></Button></header>
      <nav className="grid grid-cols-3 border-b border-border/70" aria-label="Operator creation steps">{STAGES.map((item, index) => <Button key={item} variant="ghost" onClick={() => index <= stageIndex && setStage(item)} className={`h-12 rounded-none border-b-2 font-mono text-[9px] uppercase tracking-[0.2em] ${item === stage ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}>0{index + 1} · {item}</Button>)}</nav>
      <main className="flex flex-1 flex-col justify-center py-7">
        {stage === "CLASS" && <section aria-labelledby="class-title" className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.35em] text-muted-foreground">Fracture identity system</p><h2 id="class-title" className="mt-2 text-2xl font-semibold">Choose how you stabilize reality.</h2><div className="mt-6 space-y-2">{CLASSES.map((item, index) => <Button key={item.id} variant="ghost" onClick={() => selectClass(item.id)} className={`h-auto min-h-28 w-full items-stretch justify-start rounded-none border p-4 text-left whitespace-normal ${classId === item.id ? "border-primary bg-primary/10" : "border-border bg-card/50"}`}><span className="grid w-full grid-cols-[auto_1fr] gap-4"><span className="font-mono text-[10px] text-muted-foreground">0{index + 1}</span><span><span className="block font-mono text-lg">{item.name}</span><span className="mt-1 block font-mono text-[9px] uppercase tracking-[0.2em] text-primary">{item.title} · {item.role}</span><span className="mt-2 block text-xs leading-relaxed text-muted-foreground">{item.fantasy}</span></span></span></Button>)}</div></div><OperatorPreview appearance={appearance} classId={classId} /></section>}
        {stage === "SUBCLASS" && <section aria-labelledby="subclass-title" className="grid gap-6 lg:grid-cols-[1fr_0.72fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.35em] text-primary">{selectedClass.name} signatures</p><h2 id="subclass-title" className="mt-2 text-2xl font-semibold">Choose your first specialization.</h2><div className="mt-6 grid gap-3">{subclasses.map((item) => <Button key={item.id} variant="ghost" onClick={() => setSubclassId(item.id)} className={`h-auto min-h-28 items-stretch justify-start rounded-none border p-4 text-left whitespace-normal ${subclassId === item.id ? "border-primary bg-primary/10" : "border-border bg-card/50"}`}><span><span className="font-mono text-base">{item.name}</span><span className="ml-3 font-mono text-[9px] uppercase text-primary">{item.role}</span><span className="mt-2 block text-xs leading-relaxed text-muted-foreground">{item.description}</span></span></Button>)}</div></div><div><OperatorPreview appearance={appearance} classId={classId} /><div className="mt-3 grid gap-2">{selectedClass.abilities.map((ability) => <div key={ability.slot} className="border-l-2 border-primary bg-card/40 p-3"><p className="font-mono text-[9px] text-primary">{ability.slot} · {ability.name}</p><p className="mt-1 text-[11px] text-muted-foreground">{ability.description}</p></div>)}</div></div></section>}
        {stage === "APPEARANCE" && <section aria-labelledby="appearance-title" className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="font-mono text-[10px] uppercase tracking-[0.35em] text-muted-foreground">Fracture body design</p><h2 id="appearance-title" className="mt-2 text-2xl font-semibold">Configure your field identity.</h2><p className="mt-5 font-mono text-[9px] uppercase text-primary">Body frame</p><div className="mt-2 grid grid-cols-3 gap-1">{(["LIGHT", "BALANCED", "HEAVY"] as const).map((item) => <Button key={item} size="sm" variant={bodyFrame === item ? "default" : "outline"} onClick={() => setBodyFrame(item)}>{item}</Button>)}</div><p className="mt-5 font-mono text-[9px] uppercase text-primary">Core type</p><div className="mt-2 grid grid-cols-2 gap-1">{(["LOGIC", "COMBAT", "SYSTEM", "ADAPTIVE"] as const).map((item) => <Button key={item} size="sm" variant={coreType === item ? "default" : "outline"} onClick={() => setCoreType(item)}><Cpu />{item}</Button>)}</div><p className="mt-5 font-mono text-[9px] uppercase text-primary">Armor language</p><div className="mt-2 grid grid-cols-2 gap-2">{APPEARANCES.map((item) => <Button key={item.id} variant="ghost" onClick={() => setAppearanceId(item.id)} className={`h-auto min-h-24 items-stretch justify-start rounded-none border p-3 text-left ${appearanceId === item.id ? "border-primary bg-primary/10" : "border-border bg-card/50"}`}><span><span className="flex gap-2">{[item.armor,item.cloth,item.visor].map(color => <i key={color} className="h-3 w-3 border border-border" style={{backgroundColor:color}} />)}</span><span className="mt-3 block font-mono text-xs">{item.name}</span><span className="mt-1 block font-mono text-[8px] uppercase text-muted-foreground">{item.marking}</span></span></Button>)}</div></div><OperatorPreview appearance={appearance} classId={classId} /></section>}
      </main>
      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-border/70 pt-4"><div className="flex items-center gap-2">{stageIndex > 0 && <Button variant="outline" onClick={back}><ChevronLeft /> Back</Button>}<Button onClick={next}>{stage === "APPEARANCE" && <Shield />}{stage === "APPEARANCE" ? "Begin Mission 01" : "Continue"}<ChevronRight /></Button></div><p className="font-mono text-[9px] uppercase tracking-[0.2em] text-muted-foreground">{best ? `Last run · ${best.credits} cr · ${best.kills} kills` : "Veridan insertion channel secure"}</p></footer>
    </div>
  </div>;
}
