#!/usr/bin/env python3
"""Builds src/game/coast-mask.ts: a coarse land/ocean mask traced from the illustrated "Fractured Earth" painting
(src/assets/fractured-earth-map-v2.jpg), so the in-game coastline follows the map the player sees on the star map.

Needs Pillow, numpy and scipy (offline tool, not part of the app build):
    python3 scripts/build-coast-mask.py

How it decides what is land (documented because it is a heuristic, not an authored coastline):
  - ocean = saturated blue/teal pixels, or near-black; bright low-saturation blue is snow or cloud, not ocean
  - the legend panel (right edge) and title block (top-left) are not map and are treated as ocean; authored sites there are
    re-protected in code (coastline.ts PROTECTED), never trusted to the mask
  - land components with no earth/vegetation colour are clouds and are dropped; water bodies inside land smaller than 900 px are filled
  - the Frostspire range is painted blue/white and cannot be told from ocean by colour, so it is forced by hand (polygon below)
The result is stored as run-length encoded rows on a CELL-pixel grid.
"""
import os, sys
import numpy as np
from PIL import Image, ImageDraw
from scipy import ndimage as ndi

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "src/assets/fractured-earth-map-v2.jpg")
OUT = os.path.join(ROOT, "src/game/coast-mask.ts")
CELL = 6

im = Image.open(SRC).convert("RGB")
W, H = im.size
hsv = np.asarray(im.convert("HSV")).astype(float) / 255
hue, sat, val = hsv[..., 0] * 360, hsv[..., 1], hsv[..., 2]
LEG = int(W * 0.827)
water = ((hue > 165) & (hue < 240) & (sat > 0.33) & (val > 0.10) & ~((val > 0.62) & (sat < 0.62))) | (val < 0.10)
water[:, LEG:] = True
water[: int(H * 0.075), : int(W * 0.24)] = True
land = ~water
FROST = [(398,108),(425,70),(455,38),(490,20),(530,6),(575,12),(610,30),(650,30),(690,50),(735,60),(775,58),(810,82),(835,105),(825,135),(780,150),(700,160),(620,150),(520,150),(440,150)]
pm = Image.new("L", (W, H), 0); ImageDraw.Draw(pm).polygon(FROST, fill=255)
frost = np.asarray(pm) > 0
land |= frost
land = ndi.binary_opening(land, iterations=1)
land = ndi.binary_closing(land, iterations=2)
lab, n = ndi.label(land)
earth = (hue > 15) & (hue < 165) & (sat > 0.28) & (val > 0.18)
keep = np.zeros(n + 1, bool)
for i in range(1, n + 1):
    m = lab == i
    if m.sum() < 50: continue
    keep[i] = earth[m].mean() > 0.18 or (frost & m).any()
land = keep[lab]
wl, wn = ndi.label(~land)
border = set(np.unique(np.concatenate([wl[0], wl[-1], wl[:, 0], wl[:, -1]])))
for i in range(1, wn + 1):
    if i not in border and (wl == i).sum() < 900: land[wl == i] = True
land = ndi.binary_closing(land, iterations=1)

cols, rows = (W + CELL - 1) // CELL, (H + CELL - 1) // CELL
grid = np.zeros((rows, cols), bool)
for r in range(rows):
    for c in range(cols):
        blk = land[r * CELL:(r + 1) * CELL, c * CELL:(c + 1) * CELL]
        grid[r, c] = blk.mean() >= 0.5
runs = []
flat = grid.reshape(-1)
cur, count = False, 0
for v in flat:
    if bool(v) == cur: count += 1
    else: runs.append(count); cur = bool(v); count = 1
runs.append(count)
enc = ",".join(np.base_repr(x, 36).lower() for x in runs)
with open(OUT, "w") as f:
    f.write("// GENERATED by scripts/build-coast-mask.py from src/assets/fractured-earth-map-v2.jpg. Do not edit by hand.\n")
    f.write("// Land/ocean mask of the painted Fractured Earth: row-major cells of CELL source pixels, run lengths (base 36) alternating ocean, land, ocean, ...\n")
    f.write(f"export const COAST_MASK = {{ cols: {cols}, rows: {rows}, cell: {CELL}, srcW: {W}, srcH: {H}, runs: \"{enc}\" }} as const;\n")
print("cells", cols, "x", rows, "land", grid.mean().round(3), "runs", len(runs))
